apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-db
  template:
    metadata:
      labels:
        app: card-db
    spec:
      containers:
        - name: card-db
          image: symryvvin/card-db:1.0
          envFrom:
            - configMapRef:
                name: card-db-config
            - secretRef:
                name: card-db-secret
          ports:
            - name: web
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: card-db-svc
  labels:
    app: card-db
spec:
  selector:
    app: card-db
  ports:
    - protocol: TCP
      port: 8080
      targetPort: web
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: card-db-config
data:
  DB_URL: jdbc:postgresql://search-db:5432/mtg
  DB_USERNAME: usr
---
apiVersion: v1
kind: Secret
metadata:
  name: card-db-secret
data:
  DB_PASSWORD: cGEkJHcwckQ=