apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: store-app
          image: symryvvin/order:1.0
          envFrom:
            - configMapRef:
                name: order-app-config
            - secretRef:
                name: order-app-secret
          ports:
            - name: web
              containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  labels:
    app: order-app
spec:
  selector:
    app: order-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: web
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-app-config
data:
  DB_NAME: store
  DB_HOST: store-db
  DB_PORT: "27017"
  DB_USERNAME: user
  STORE_SERVICE_URI: store-svc.mtg:8080
  AXON_SERVER: axonserver:8124
---
apiVersion: v1
kind: Secret
metadata:
  name: order-app-secret
data:
  DB_PASSWORD: cGFzcw==