apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: symryvvin/api-gateway:1.0
          envFrom:
            - configMapRef:
                name: gateway-config
          ports:
            - name: web
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: web
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  IDENTITY_SERVICE_URI: http://identity-svc.mtg:8080
  STORE_SERVICE_URI: http://store-svc.mtg:8080
  SEARCH_SERVICE_URI: http://card-db-svc.mtg:8080
  ORDER_SERVICE_URI: http://order-svc.mtg:8080
  FRONTEND: http://frontend.mtg:7777
  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz6nSQ0mkeF3KTHvdXVmY
    k2Pxt0qNPpcTdRWYfPuhThorFdNUW2gzWyfFlo0/S9tCSVhd71M3dNN220S94QN+
    kcoqF2V5FDlOWpAsVb6Rjp5yoeyNB94VXwMegdmRA2eLhG89ncgHu7vsPjxoAgce
    LRbOHYYypSUKdYruCObBKDqS0JO8vzqg80bnm2xmGk5gEKjSha2DXx3hyAMSfnOG
    1GE/r8W35472kq1X04zm2iuoCCSwifiSi5GF4Lr1seLibprai9uctkhEO2TJeHol
    1sEiPXLSDu5XOIAhzUrHLjx3tzpeYdLSyGwhlq0DOluy6hDAl/JR/GzEgEuNBWTZ
    2wIDAQAB
    -----END PUBLIC KEY-----