fullnameOverride: search-db
postgresqlUsername: usr
postgresqlPassword: pa$$w0rD
postgresqlDatabase: mtg

service:
  type: NodePort
  port: 5432

persistence:
  enabled: true
  size: 512Mi

resources:
  requests:
    memory: 256Mi
    cpu: 250m
