server:
  port: 8081
  servlet:
    context-path: /rest/search/

card:
  import:
    time: 0 00 03 * * ?
  data:
    remote: https://api.scryfall.com/bulk-data/all_cards
    local: /home/aizen/cards/all-data

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 100