fullnameOverride: store-db
auth:
  rootPassword: pass
  username: user
  password: pass
  database: store

useStatefulSet: true

service:
  type: LoadBalancer
  port: 27017

persistence:
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 250m